### PR TITLE
:sparkles: Implement definition typescript file to lib

### PR DESCRIPTION
**Pull request by paulocesarpcfj**
Implementing d.ts file to the lib

### CODE REVIEW

**Review by bernardbr — APPROVED** [review]
👌

**Comment by tiagor87** [comment]
I did'nt understant the file, it's nothing related to the main JS. I think you missed some configuration at the generator.

**Review by tiagor87 — CHANGES_REQUESTED** [review]
I did'nt understant the file, it's nothing related to the main JS. I think you missed some configuration at the generator.

**Review by bernardbr — CHANGES_REQUESTED** [review]
@paulocesarpcfj you generated the d.ts from yargs and not from the main.js

**Pull request closed without merging**
